### ISSUE TITLE
Лампа не загружает торренты с jackett

### ISSUE THREAD

**Issue by DotMan2000** [yumata/lampa-source#113]
Всем привет. У меня есть очень странная странная проблема.
Вот захожу, значит, на фильм. Хочу загрузить его торренты. 
Но не получается, говорит, что парсер недоступен:
![photo_2022-11-23_11-02-51](https://user-images.githubusercontent.com/66158775/203462536-77193e0e-99e6-42c4-af3f-dc2a3e9db1a1.jpg)
Но это не так, потому что парсер отвечает, и даже говорит, сколько он нашёл торрентов:
![photo_2022-11-23_11-02-56](https://user-images.githubusercontent.com/66158775/203462586-5f1ceea0-af9d-41db-b99b-c0e97f175fa2.jpg)
Логи лампы (не обращайте внимание на разницу запросов, скрины сделаны в разное время, но суть одна и та же, он отвечает таким образом на любой фильм):
![Снимок экрана 2022-11-23 110955](https://user-images.githubusercontent.com/66158775/203462642-5b18f681-0975-4e72-ae9b-f5a84e346fa0.png)
Это очень странно, может с настройками лампы что то не так, вот настройки:
![Снимок экрана 2022-11-23 111757](https://user-images.githubusercontent.com/66158775/203462965-22f6efa9-b270-48d7-9221-eb50d81a12fc.png)
В общем, прошу помощи у работяг, а то без бесплатных фильмов плохо:(
Заранее спасибо.

**Comment by totavok8** [comment]
Для начало проверить чтобы была галочка Allow CORS в настройках жакета. (без неё в лампе работать не будет)

**Comment by DotMan2000** [comment]
> Для начало проверить чтобы была галочка Allow CORS в настройках жакета. (без неё в лампе работать не будет)

Спасибо! А то я уже дебажить лампу начал) А оказывается что просто корс)

**Comment by ratnikov-d** [comment]
> Для начало проверить чтобы была галочка Allow CORS в настройках жакета. (без неё в лампе работать не будет)

Блин, спасибо тебе. Я тоже всю голову сломал и уже сидел изучал расширенные логи. А оказалось дело в одной галочке.

**Comment by serjevski** [comment]
Присоединюсь к благодарностям!

**Comment by photobrand** [comment]
Тоже присоединюсь к благодарностям!

**Comment by sNc-DAntES** [comment]
> Для начало проверить чтобы была галочка Allow CORS в настройках жакета. (без неё в лампе работать не будет)

Поставил галочку, но всё равно Лампа не видит сервер, хотя с самого устройства на Jackett можно зайти. В чем ещё может быть проблема?

**Comment by lexxnsk** [comment]
а как полностью выключить АПИ ключ?

**Comment by GamesIS** [comment]
Та же проблема
