### ISSUE TITLE
Feature Request: Play torrent already added to torrserver

### ISSUE THREAD

**Issue by Makeshift** [yumata/lampa-source#122]
Hi,

Sometimes I find it inconvenient to search for torrents via Lampa+Jackett and manually add things I'd like to watch direct to Torrserver.

Would it be possible to have an option to check what's already on Torrserver and play directly from that list?

Thank you

**Comment by yumata** [comment]
Menu - my torrents. Pulls a list of torrents that have been added to Torrserver.

**Comment by Makeshift** [comment]
Oh, hah, I'm stupid. Thank you!
