### ISSUE TITLE
Filter menu's Original language list not Chinese

### ISSUE THREAD

**Issue by aston314** [yumata/lampa-source#150]
Original language list do not show Chinese but Russian In Filter menu when I use Chinese language.
<img width="1407" alt="截屏2023-06-11 10 52 20" src="https://github.com/yumata/lampa-source/assets/2224932/1afcd2f2-24c7-451e-ab77-4fec16c2c36d">

**Comment by yumata** [comment]
Fixed

**Comment by aston314** [comment]
Thank you
