### ISSUE TITLE
Title of the notification

### ISSUE THREAD

**Issue by aston314** [yumata/lampa-source#151]
![Screenshot (1)](https://github.com/yumata/lampa-source/assets/2224932/6b251eae-4fc2-4a2f-a5f5-0e5a9b802efe)

When I am using the Chinese language, the movie or TV show titles in the notifications are still in Russian. Could you please determine the language being used and if it is not Russian, change the title to the original language? Replace "title: data.card.title || data.card.name" with "title: data.card.title || data.card.original_name". Thank you.

**Comment by yumata** [comment]
I don't know how to fix it yet, but I'll think of something later.

**Comment by aston314** [comment]
in [‎src/interaction/notice/cub.js]:
replace:

return {
                    time: item.time || Utils.parseToDate(item.date).getTime(),
                    title: data.card.title || data.card.name,
                    text: text,
                    poster: data.card.poster ? data.card.poster : data.card.img ? data.card.img : data.card.poster_path,
                    card: data.card,
                    labels: labels
                }

with:

                return {
                    time: item.time || Utils.parseToDate(item.date).getTime(),
                    title: !Lang.selected(['ru', 'uk', 'be']) ? (data.card.title || data.card.original_name) : (data.card.title || data.card.name),
                    text: text,
                    poster: data.card.poster ? data.card.poster : data.card.img ? data.card.img : data.card.poster_path,
                    card: data.card,
                    labels: labels
                }

**Comment by yumata** [comment]
Damn, this is a great idea.

**Comment by yumata** [comment]
Fixed.
