### ISSUE TITLE
Country of Origin on the detailed page

### ISSUE THREAD

**Issue by aston314** [yumata/lampa-source#153]
<img width="858" alt="截屏2023-06-23 10 45 29" src="https://github.com/yumata/lampa-source/assets/2224932/7ec19829-ac9b-4c7f-bc15-53793f2b1af3">
When I was reading the detailed description of the movie, I noticed that the country of origin was in Russian. Can it be changed to the language of my choice?

**Comment by yumata** [comment]
Fixed.
