### ISSUE TITLE
./plugins_black_list.json - no network connection.

### ISSUE THREAD

**Issue by eboboshka** [yumata/lampa-source#183]
The application takes a very long time to launch, about 2 minutes.
After loading, an error is displayed in the console
`./plugins_black_list.json - no network connection.`

All other things are working.
The application is installed from App market Samsung

Samsung Tizen (2501.1)
Lampa v2.0.2

https://github.com/yumata/lampa-source/blob/840bba30cb3677b28aa0e3a5444fc76ab16194bb/src/utils/plugins.js#L154

**Comment by yumata** [comment]
This does not affect the download, if this file is not there, it will give an error and continue downloading, usually this takes 1-2 miles seconds.

**Comment by eboboshka** [comment]
Thank you for your reply. I will go to find out what the reason for the long loading time is
