### ISSUE TITLE
Добавление параметров для tmdb/cub

### ISSUE THREAD

**Issue by gwynnbleiidd** [yumata/lampa-source#188]
Привет, для Lampa.Activity
Можно добавить параметры

1. watch_region
2. with_watch_providers
3. with_networks
Первые два работают с фильмами, третий на сериалах в ендпоинтах discover
Что бы вытягивать с tmdb/cub фильмы по сетям)

**Comment by yumata** [comment]
Там есть параметр ```.card```  в Activity

**Comment by gwynnbleiidd** [comment]
> Там есть параметр `.card` в Activity

Сорян, я не уточнил самое важное) А больше про нативное формирование раздела

```
Lampa.Activity.push({
        url: "discover/tv",
        title: "Мультфильм - CUB",
        component: "category_full",
        genre: ****
        source: "tmdb",
        card_type: true,
        page: 1,
      });
```

Вот так можно сделать раздел мультиков, я методом тыка нашел что принимается параметр keywords.
Но вот остальные параметры для ТМД не принимаются, а именно
```
watch_region: 'ua',
with_watch_providers: 8,
with_networks: 213,
```

Если сможешь добавить будет супер. В кубе я так понимаю их нет. Но если добавишь прокидывание в ТМДБ будет супер
