### ISSUE TITLE
Встроенный торрент-клиент

### ISSUE THREAD

**Issue by qarkai** [yumata/lampa-source#21]
Пожалуйста, рассмотрите возможность добавления торрент-клиента. Например, [WebTorrent](https://webtorrent.io/docs), [torrent-stream](https://github.com/mafintosh/torrent-stream), [Webtor](https://github.com/webtor-io/embed-sdk-js) и т.п.

**Comment by yumata** [comment]
Не работает, проверено.

**Comment by qarkai** [comment]
Что именно не работает?
