### ISSUE TITLE
YouTube let needclick 

### ISSUE THREAD

**Issue by gwynnbleiidd** [yumata/lampa-source#222]
Привет! Пытаюсь понять как она работает https://github.com/yumata/lampa-source/blob/f41b2fc8c0f2bad2cd802ba149e3fbef00b19a4d/src/interaction/player/youtube.js#L9

Вроде никакого определения нет кроме комментария
На AppleTv не срабатывает автозапуск, хотя с pwa приложения то же. Вдруг таки можно поправить)

**Comment by yumata** [comment]
Хром блокирует автозапуск, думал что это проблема только на мобилах, но оказалось на всех платформах такая проблема.
