### ISSUE TITLE
Несколько уровней в Настройках

### ISSUE THREAD

**Issue by and7ey** [yumata/lampa-source#229]
Нужна возможность добавлять несколько уровней в настройках Лампы.
Сейчас возможна лишь следующая структура (через [SettingsApi](https://github.com/yumata/lampa-source/blob/main/src/components/settings/api.js)):

`Настройки - Плагин`

а нужна структура вида

`Настройки - Интерфейс - Плагин`

(где вместо Интерфейса может быть что угодно - например, `Остальное`).

Иначе сейчас все плагины добавляют свои настройки в корень и там получается свалка.

**Comment by bylampa** [comment]
Ну так пусть добавляют не в корень, а создают в настройках компонента ещё компонент

**Comment by and7ey** [comment]
Возможно, я чего-то не знаю - в настройки интерфейса, например, разве можно добавить настройки? Именно настройки через SettingsApi, а не кастомный компонент? 

Если можно, то покажите плз пример кода.

**Comment by and7ey** [comment]
Спасибо, сделал в https://github.com/and7ey/lampa/blob/main/head_filter.js.
