### ISSUE TITLE
Подскажите как в браузере тестировать

### ISSUE THREAD

**Issue by Dukobpa3** [yumata/lampa-source#62]
У меня работают стрелочки и кнопки "Х", "Escape"(отрабатывают как бек).
Не могу найти "ок", по идее пробел если я правильно понял по коду, но почему-то не работает.

**Comment by Dukobpa3** [comment]
Макбук, браузер хром

**Comment by Dukobpa3** [comment]
Хм, в сафари заработало

**Comment by Nemiroff** [comment]
OK = Enter

**Comment by Dukobpa3** [comment]
Я уже разобрался но почему-то работает только в сафари. В хроме ни в какую.
