### ISSUE TITLE
штатный плеер webos 6

### ISSUE THREAD

**Issue by aabytt** [yumata/lampa-source#8]
https://github.com/yumata/lampa-source/blob/79990a7fc8332c761cf990c9040653e4a1969c13/src/interaction/player.js#L219

выяснилось, что на webos 6.х они снова поменяли ID приложения плеера на com.webos.app.mediadiscovery
Итого возможные варианты 
com.webos.app.photovideo
com.webos.app.smartshare
com.webos.app.mediadiscovery

**Comment by yumata** [comment]
Добавлено
