### ISSUE TITLE
Дабавить для андройдов вывод версии apk полученную через AndroidJS.appVersion()

### ISSUE THREAD

**Issue by usmanec** [yumata/lampa-source#82]
Каждый день в группе лампы для андройд ТВ звучат дурацкие вопросы, типа:

> у меня сейчас установлена версия 1.3.9, всё вроде работает, стоит ли обновлятся на 7.7.7 -80 ?

https://t.me/lampa_android/94788

Предлагаю в about добавить версию apk полученную через `AndroidJS.appVersion()`

**Comment by yumata** [comment]
Добавил.
