### ISSUE TITLE
Подписи аудиодорожек

### ISSUE THREAD

**Issue by aabytt** [yumata/lampa-source#92]
https://github.com/yumata/lampa-source/blob/740d6243fdb51d7a46ac0a2fe9524ae78b4e745c/src/interaction/player/panel.js#L214
https://github.com/yumata/lampa-source/blob/740d6243fdb51d7a46ac0a2fe9524ae78b4e745c/src/interaction/player/panel.js#L215
`Каналов` и `Тип` не попали в переводы интерфейсов, может их (подписи, не значения) вообще убрать/заменить универсальным и менее громоздким вариантом?
Сейчас
`1 / rus / MVO TVShows / Каналов: 6 / Тип: ac3`
vs универсальный вариант для всех языков интерфейса
`1 / rus / MVO TVShows / 6 Ch / ac3`

**Comment by yumata** [comment]
Исправил)
